[server]
port = 8081

[database]
type="postgres"
host="172.16.100.200"
database="project"
schema ="sky_website"
port=25432
username= "postgres"
password= "Sky@2024"


[jwt]
#可以使用base64生成
secret = "your-super-secret-key-that-is-at-least-32-bytes-long"
# 签发者 应用名或者域名或者ip+port
issuer = "rust-web-template"
# JWT  token过期时间，单位：分钟
acc_expiration_hour = 1
# JWT token刷新时间，单位：分钟
ref_expiration_hour = 2
